import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Data from '../../public/data.json'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //  console.log(Data.recipes)

  const recipes = Data.recipes;

  return (
    <>
      <main>
        <main>

          <section class="py-5 text-center banner">
            <div class="row py-lg-5">
              <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-bold">Гладни ли сте?</h1>
                <p class="lead">Вижте какво имате в хладилника и разберете какво можете да сготвите</p>
                <div class="input-group mb-3 search">
                  <input type="text" class="form-control" placeholder="Search products" aria-label="Recipient's username" aria-describedby="button-addon2" />
                  <button class="btn btn-secondary" type="button" id="button-addon2"><i class="bi bi-search"> Search</i></button>
                </div>
              </div>
            </div>
          </section>

          <div class="album py-5 bg-light">
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {
                  recipes.map((recipe) => {
                    return (
                      <div class="col">
                        <div class="card shadow-sm">
                          {/* <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><text x="50%" y="50%" fill="#eceeef" dy=".3em"><img src="public\images\recipe1.jpg" /></text></svg> */}

                          {/* <a href={"/recipes/" + recipe.id}> <img src={`/images/${recipe.image ? recipe.image : "nophoto.png"}`} alt={recipe?.title} /></a> */}
                          {/* <div className='card-image'> */}
                          <img src={`/images/${recipe.image ? recipe.image : "nophoto.png"}`} alt={recipe?.title} className="card-image"/>
                          {/* </div> */}
                          <div class="card-body text-black">

                            <div class="card-text">
                                <a href={"/recipes/" + recipe.id} className='card-title'>
                                  <strong>{recipe.title}</strong>
                                </a>
                            </div>
                            <div className='card-ingredients'>
                              Products needed:
                              <br></br>
                              <blockquote className='card-ingredients'>
                                {
                                  recipe.ingredients.map((ingredient, index) => {
                                    return (
                                      (index > 0) ? `, ${ingredient}` : ingredient
                                    )
                                  })
                                }
                                {/* {recipe?.ingredients.slice(0, 5).map((ingredient, index) => (
                                  <div key={index}>{ingredient}</div>
                                 ))}
                                    {recipe?.ingredients.length > 5 && (
                                      <div>etc.</div>
                                    )} */}
                              </blockquote>
                            </div>
                            <div class="d-flex justify-content-between align-recipes-center mt-4 border-top pt-2">
                              <a href={"/recipes/" + recipe.id} class="btn btn-sm btn-secondary">View</a>
                              <small class="text-muted"><i class="bi bi-hourglass-split"></i>{recipe.time}min</small>
                            </div>
                          </div>
                        </div>
                      </div>
                    )
                  })
                }
              </div>
            </div>
          </div>
        </main>
      </main>

      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
    </>
  )
}
